### ISSUE TITLE
[Bug]: Multi-GPU Training not Working in 0.7.1 and 0.8.5

### ISSUE THREAD

**Issue by mstapelberg** [materialsvirtuallab/matgl#195]
### Email (Optional)

myless@mit.edu

### Version

v0.8.5 and v0.7.1

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

First off, thank you all so far for your help with getting me started on this. I think at this point my issue has become more appropriate for a bug fix. 

I am trying to train a model using multiple GPUs and opened the discussion in https://github.com/materialsvirtuallab/matgl/discussions/188

I first had an issue using 0.8.5 MatGL and PyTorch = 2.1.1 (for CUDA 11.8) where I encountered the same error in https://github.com/materialsvirtuallab/matgl/discussions/149 : 

```python
Traceback (most recent call last):
  File "/home/u2019/work/ml/GPU-test/train.py", line 45, in <module>
    dataset = M3GNetDataset(
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/matgl/graph/data.py", line 255, in __init__
    super().__init__(name=name)
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/dgl/data/dgl_dataset.py", line 112, in __init__
    self._load()
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/dgl/data/dgl_dataset.py", line 203, in _load
    self.process()
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/matgl/graph/data.py", line 278, in process
    line_graph = create_line_graph(graph, self.threebody_cutoff)  # type: ignore
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/matgl/graph/compute.py", line 146, in create_line_graph
    l_g, triple_bond_indices, n_triple_ij, n_triple_i, n_triple_s = compute_3body(graph_with_three_body)
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/matgl/graph/compute.py", line 24, in compute_3body
    first_col = g.edges()[0].numpy().reshape(-1, 1)
  File "/home/u2019/miniconda3/envs/py310/lib/python3.10/site-packages/torch/utils/_device.py", line 62, in __torch_function__
    return func(*args, **kwargs)
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```
This error is happening when the actual dataset is being created using M3GNetDataset. It was implemented in this commit : https://github.com/materialsvirtuallab/matgl/commit/e825b75ccec8348e07ea4052e220c44b3ea168a2 

Does this even need to be run on a GPU? It seems like due to hard coding it to run on CPU, that any torch.set_default_device('cuda') should come after creating the dataset itself. However looking through issue https://github.com/materialsvirtuallab/matgl/issues/94 Prof. Ong states that torch.device('cuda') must come first. 

Nevertheless I was suggested to downgrade PyTorch and it's dependencies to 2.0.1 (and I also downgraded matgl to 0.7.1), and following the training example given by SmallBearC, I was able to get a single GPU to run. 

However when attempting to setup multi-gpu use, I got an error in the MGLDataLoader: 
```python
Traceback (most recent call last):
  File "/home/myless/Potential_Training/V-Cr-Ti/Test_1/train.py", line 77, in <module>
    train_loader, val_loader, test_loader = MGLDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/matgl/graph/data.py", line 78, in MGLDataLoader
    train_loader = GraphDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1451, in __init__
    self.dist_sampler = _create_dist_sampler(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1281, in _create_dist_sampler
    return DistributedSampler(dataset, **dist_sampler_kwargs)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    num_replicas = dist.get_world_size()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1196, in get_world_size
    return _get_group_size(group)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 576, in _get_group_size
    default_pg = _get_default_group()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
```

I was given the suggestion by a maintainer to change torch/utils/data/distributed.py
```python
def __iter__(self) -> Iterator[T_co]:
        if self.shuffle:
            # deterministically shuffle based on epoch and seed
            g = torch.Generator()
            g.manual_seed(self.seed + self.epoch)
            indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
        else:
            indices = list(range(len(self.dataset)))  # type: ignore[arg-type]
```
To: 
```python
def __iter__(self) -> Iterator[T_co]:
        if self.shuffle:
            # deterministically shuffle based on epoch and seed
            #work around added to make matgl work
            if torch.cuda.is_available():
                device = "cuda"
            else:
                device = "cpu"
            g = torch.Generator(device=device)
            g.manual_seed(self.seed + self.epoch)
            indices = torch.randperm(len(self.dataset), generator=g).tolist()  # type: ignore[arg-type]
        else:
            indices = list(range(len(self.dataset)))  # type: ignore[arg-type]
```
but the same error occurred. I did some digging and I found my error being caused by when the GraphDataLoader is trying to use DDP for the Training Data. It is likely an issue with how the model is being split and sent to the gpus. 

There seems to be two bugs or issues here. In Version 0.8.5, I believe there is an issue with the _compute_3body() in matgl/src/matgl/graph/compute.py 

```python
    n_atoms = g.num_nodes()
    first_col = g.edges()[0].cpu().numpy().reshape(-1, 1)
    all_indices = np.arange(n_atoms).reshape(1, -1)
```

Could this perhaps be fixed by moving things onto the gpu after the dataset has been created? 

The bug with 0.7.1 seems to be something related to the ddp strategy of loading the dataset onto the multiple gpus for training. This seems more difficult to fix for the matgl team and since it is happening with an older package version, perhaps the bug in 0.8.5 is better to focus on? 

I have pasted the code that I was using on matgl==0.7.1 and the output from slurm. 

Thank you, 
Myles 

### Code snippet

```python
from __future__ import annotations

import os, json
import shutil
import warnings

import numpy as np
import pytorch_lightning as pl
from dgl.data.utils import split_dataset
from pytorch_lightning.loggers import CSVLogger
from pymatgen.io.vasp.outputs import Vasprun

import matgl
from matgl.ext.pymatgen import Structure2Graph, get_element_list
from matgl.graph.data import M3GNetDataset, MGLDataLoader, collate_fn_efs
from matgl.models import M3GNet
from matgl.utils.training import PotentialLightningModule

# To suppress warnings for clearer output
warnings.simplefilter("ignore")

import torch
torch.set_default_device('cuda')
AVAIL_GPUS = torch.cuda.device_count()

folder_path = './test_xml_data'
#folder_path = './data'
xml_files = [f for f in os.listdir(folder_path) if f.endswith(".xml")]

#initialize empty arrays
structures = []
energies = []
forces = []
stresses = []
errors = []

for xml_file in xml_files:
	xml_file_path = os.path.join(folder_path, xml_file)

	try:
		vrun = Vasprun(xml_file_path)
		#print(f"File: {xml_file} loaded")
		for i in range(len(vrun.ionic_steps)):
			structures.append(vrun.ionic_steps[i]['structure'])
			energies.append(vrun.ionic_steps[i]['e_fr_energy'])
			forces.append(vrun.ionic_steps[i]['forces'])
			stresses.append(vrun.ionic_steps[i]['stress'])
	except Exception as e:
		error_message = f"Error parsing {xml_file}: {str(e)}"
		errors.append(error_message)
		print(error_message)

with open('./bad_vasprun.txt', 'w') as file:
	for error_message in errors:
		file.write(f"{error_message}\n")

labels = {
	"energies": energies,
	"forces": forces,
	"stresses": stresses,
}

print(f"{len(structures)} downloaded from MP.")
#formatted_data = json.dumps(labels, indent=4)

#with open("labels.json","w") as json_file:
	#json_file.write(formatted_data)
element_types = get_element_list(structures)
converter = Structure2Graph(element_types=element_types, cutoff=5.0)
dataset = M3GNetDataset(
	threebody_cutoff=4.0,
	structures=structures,
	converter=converter,
	energies=energies,
	forces=forces,
	stresses=stresses, #changed when downgrading to 0.7.1
	#labels=labels,
)
train_data, val_data, test_data = split_dataset(
	dataset,
	frac_list=[0.8, 0.1, 0.1],
	shuffle=True,
	random_state=42,
)
train_loader, val_loader, test_loader = MGLDataLoader(
	train_data=train_data,
	val_data=val_data,
	test_data=test_data,
	collate_fn=collate_fn_efs,
	batch_size=16,
	num_workers=0,
	use_ddp=True,
	pin_memory=True,
	generator=torch.Generator("cuda"),
)

model = M3GNet(
	element_types=element_types,
	is_intensive=False,
	use_smooth=True
)
lr = 1e-4
lit_module = PotentialLightningModule(model=model,lr=lr)

# If you wish to disable GPU or MPS (M1 mac) training, use the accelerator="cpu" kwarg.
logger = CSVLogger("logs", name="M3GNet_training")
# Inference mode = False is required for calculating forces, stress in test mode and prediction mode
trainer = pl.Trainer(max_epochs=1, accelerator="cuda", devices=4, strategy="ddp", logger=logger, inference_mode=False)
#trainer = pl.Trainer(max_epochs = 1, accelerator='auto', logger=logger, inference_mode=False)
trainer.fit(model=lit_module, train_dataloaders=train_loader, val_dataloaders=val_loader)

trainer.test(dataloaders=test_loader)

model_export_path = './trained_model/mgl.m3g_out'
model.save(model_export_path)

model = matgl.load_model(path = model_export_path)
```

### Log output

```shell
Traceback (most recent call last):
  File "/home/myless/Potential_Training/V-Cr-Ti/Test_2/old_train.py", line 85, in <module>
    train_loader, val_loader, test_loader = MGLDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/matgl/graph/data.py", line 78, in MGLDataLoader
    train_loader = GraphDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1451, in __init__
    self.dist_sampler = _create_dist_sampler(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1281, in _create_dist_sampler
Traceback (most recent call last):
  File "/home/myless/Potential_Training/V-Cr-Ti/Test_2/old_train.py", line 85, in <module>
    return DistributedSampler(dataset, **dist_sampler_kwargs)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    train_loader, val_loader, test_loader = MGLDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/matgl/graph/data.py", line 78, in MGLDataLoader
    num_replicas = dist.get_world_size()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1196, in get_world_size
    train_loader = GraphDataLoader(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1451, in __init__
    return _get_group_size(group)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 576, in _get_group_size
    self.dist_sampler = _create_dist_sampler(
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/dgl/dataloading/dataloader.py", line 1281, in _create_dist_sampler
    default_pg = _get_default_group()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    return DistributedSampler(dataset, **dist_sampler_kwargs)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/utils/data/distributed.py", line 68, in __init__
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
    num_replicas = dist.get_world_size()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1196, in get_world_size
    return _get_group_size(group)
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 576, in _get_group_size
    default_pg = _get_default_group()
  File "/home/myless/.mambaforge/envs/matgl-gpu/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 707, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
srun: error: gpu-rtx6000-02: task 2: Exited with exit code 1
srun: error: gpu-rtx6000-02: tasks 0-1: Exited with exit code 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JonathanSchmidt1** [comment]
Maybe this is helpful for you. I had some problems getting multi-gpu training to work but changing torch/utils/data/distributed.py in the way suggested by you worked for me with the following library versions:
dgl.version  '1.1.3+cu118'
matgl.version '0.9.1'
torch.version '2.0.1+cu118'
for reference my training script. The only difference I noticed is that I do not use ddp=True for the dataloader, I think PL should take care of that:

```from __future__ import annotations
import os
import shutil
import warnings
import zipfile
from functools import partial
import torch
torch.set_default_device("cuda")
import pytorch_lightning as pl
from dgl.data.utils import split_dataset
from pymatgen.core import Structure
from pytorch_lightning.loggers import CSVLogger
from tqdm import tqdm
from matgl.ext.pymatgen import Structure2Graph, get_element_list
from matgl.graph.data import M3GNetDataset, MGLDataLoader, collate_fn
from matgl.models import M3GNet
from matgl.utils.io import RemoteFile
from matgl.utils.training import ModelLightningModule

# To suppress warnings for clearer output
warnings.simplefilter("ignore")
import pickle
import numpy as np
entries = pickle.load(open('entries.pickle','rb'))

print("finished loading")
structures = []
e_form_per_atom = []
for el in tqdm(entries):
    structures.append(el.structure)
    e_form_per_atom.append(el.data['e_form'])


# get element types in the dataset
elem_list = get_element_list(structures)
# setup a graph converter
converter = Structure2Graph(element_types=elem_list, cutoff=5.0)
# convert the raw dataset into MEGNetDataset
mp_dataset = M3GNetDataset(
    threebody_cutoff=5.0, structures=structures, converter=converter, labels={"eform": eform_per_atom}
)
print("dataset")
train_data, val_data, test_data = split_dataset(
    mp_dataset,
    frac_list=[0.8, 0.1, 0.1],
    shuffle=True,
    random_state=42,
)
my_collate_fn = partial(collate_fn, include_line_graph=True)
train_loader, val_loader, test_loader = MGLDataLoader(
    train_data=train_data,
    val_data=val_data,
    test_data=test_data,
    collate_fn=my_collate_fn,
    batch_size=2,
    num_workers=0,
#   	use_ddp=True,
    generator=torch.Generator(device='cuda')
)


# setup the architecture of MEGNet model
model = M3GNet(
        element_types=elem_list,
        is_intensive=True,
        readout_type="set2set",
        ).cuda()
# setup the MEGNetTrainer
lit_module = ModelLightningModule(model=model)
print("starting trainer")
logger = CSVLogger("logs", name="M3GNet_training")
trainer = pl.Trainer(max_epochs=20, accelerator="gpu", logger=logger, num_nodes=2)
trainer.fit(model=lit_module, train_dataloaders=train_loader, val_dataloaders=val_loader)
```

**Comment by kenko911** [comment]
Hi @mstapelberg, sorry for the late reply. Please upgrade the latest version of matgl and do not use ddp=True in MGLDataLoader Class as suggested by @JonathanSchmidt1. It should work and please let me know if any problems.
