### ISSUE TITLE
[Bug]: ValueError: Bad serialized model or bad model name. It is possible that you have an older model cached. Please clear your cache by running `python -c "import matgl; matgl.clear_cache()"`

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [materialsvirtuallab/matgl#250]
### Version

matgl-1.0.0

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

when I try to load the model it showing this error. even I tried to remove cache but still I am facing the same issue 

### Code snippet

```python
import matgl

# Clear the matgl cache without confirmation
matgl.config.clear_cache(confirm=True)

model = matgl.load_model('M3GNet-MP-2018.6.1-Eform')
```

### Log output

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File ~/miniconda3/envs/cdvae/lib/python3.10/site-packages/matgl/utils/io.py:210, in load_model(path, **kwargs)
    208 classname = d["@class"]
--> 210 mod = __import__(modname, globals(), locals(), [classname], 0)
    211 cls_ = getattr(mod, classname)

File ~/miniconda3/envs/cdvae/lib/python3.10/site-packages/matgl/models/__init__.py:5
      3 from __future__ import annotations
----> 5 from ._m3gnet import M3GNet
      6 from ._megnet import MEGNet

File ~/miniconda3/envs/cdvae/lib/python3.10/site-packages/matgl/models/_m3gnet.py:17
     15 from typing import TYPE_CHECKING, Literal
---> 17 import dgl
     18 import torch

File ~/miniconda3/envs/cdvae/lib/python3.10/site-packages/dgl/__init__.py:16
     14 from .backend import backend_name, load_backend  # usort: skip
---> 16 from . import (
     17     container,
     18     cuda,
     19     dataloading,
     20     function,
     21     ops,
...
    215         "Bad serialized model or bad model name. It is possible that you have an older model cached. Please "
    216         'clear your cache by running `python -c "import matgl; matgl.clear_cache()"`'
    217     ) from err

ValueError: Bad serialized model or bad model name. It is possible that you have an older model cached. Please clear your cache by running `python -c "import matgl; matgl.clear_cache()"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
Hi @HarshaSatyavardhan, I am unable to reproduce the error you have and we also have a united test to check all available models working. Please try to remove  the current version of MatGL and reinstall it to see if the error still exists. I guess you have a previous version of MatGL installed before.

**Comment by HarshaSatyavardhan** [comment]
when I run this command to clear the cache  `mgl clear` I am getting the below error 
I have tried uninstalling and installing the latest version and no luck 
FYI it used to work two days back. all of a sudden it started to throw these weird error. I have no idea what's happening 

 ```
Traceback (most recent call last):
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/bin/mgl", line 5, in <module>
    from matgl.cli import main
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/matgl/cli.py", line 16, in <module>
    from matgl.ext.ase import Relaxer
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/matgl/ext/ase.py", line 29, in <module>
    from matgl.graph.converters import GraphConverter
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/matgl/graph/converters.py", line 7, in <module>
    import dgl
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/graphbolt/__init__.py", line 8, in <module>
    from .base import *
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/dgl/graphbolt/base.py", line 8, in <module>
    from torchdata.datapipes.iter import IterDataPipe
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/torchdata/__init__.py", line 9, in <module>
    from . import datapipes
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/torchdata/datapipes/__init__.py", line 9, in <module>
    from . import iter, map, utils
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils.data.datapipes.utils.common import _check_unpickable_fn, DILL_AVAILABLE
ImportError: cannot import name 'DILL_AVAILABLE' from 'torch.utils.data.datapipes.utils.common' (/home2/harsha.vasamsetti/miniconda3/envs/slices2/lib/python3.9/site-packages/torch/utils/data/datapipes/utils/common.py)
```

**Comment by BenjaminMD** [comment]
@kenko911, I'm encountering the same problem on a completely fresh install of matgl.
