### ISSUE TITLE
FYI: Upstream dependency conflict with `dgl`/`torchdata`

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsvirtuallab/matgl#295]
### Version

1.1.2

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

7 hrs ago, `torchdata` updated to 0.8.0, which in turn breaks the most recent release of `dgl`, which in turn in turn breaks the most recent release of `matgl`.

Doing `pip install matgl 'numpy<2'` and `import dgl` in a fresh environment confirms this. This is potentially related to https://github.com/dmlc/dgl/issues/7623.

I just wanted to let you know when you inevitably start seeing the CI fail for unusual reasons.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/graphbolt/__init__.py", line 8, in <module>
    from .base import *
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/dgl/graphbolt/base.py", line 8, in <module>
    from torchdata.datapipes.iter import IterDataPipe
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/torchdata/datapipes/__init__.py", line 11, in <module>
    from . import iter, map, utils
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/torchdata/datapipes/iter/__init__.py", line 79, in <module>
    from torchdata.datapipes.iter.util.cacheholder import (
  File "/home/rosen/software/miniconda/envs/test/lib/python3.11/site-packages/torchdata/datapipes/iter/util/cacheholder.py", line 24, in <module>
    from torch.utils._import_utils import dill_available
ModuleNotFoundError: No module named 'torch.utils._import_utils'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alinelena** [comment]
yes, we have the same I suspect is the torch version.

**Comment by ElliottKasoar** [comment]
> yes, we have the same I suspect is the torch version.

For reference, we have two sets of tests before and after errors:

https://github.com/stfc/janus-core/actions/runs/10162512181/job/28103327718
https://github.com/stfc/janus-core/actions/runs/10183389048/job/28196973528

Both use `torch` 2.2.1, `dgl` 2.1.0 and `matgl` 1.1.2, but `torchdata` changes from 0.7.1 to 0.8.0

**Comment by kenko911** [comment]
Hi @Andrew-S-Rosen, @alinelena and @ElliottKasoar, thank you all for your information. I think the problem comes from the latest version of torchdata. Now I set up the upper bound of torchdata and it should work now. Thanks!
