### ISSUE TITLE
[Bug]: FileNotFoundError: Cannot find DGL C++ graphbolt library at /usr/local/lib/python3.9/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.4.0.so

### ISSUE THREAD

**Issue by xiaohang007** [materialsvirtuallab/matgl#334]
### Email (Optional)

hangxiao@ln.edu.hk

### Version

v1.1.3

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I used this dockerfile to set up the env for matgl. 
```bash
FROM python:3.9.17
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install matgl jupyter lxml
ENV DGLBACKEND=pytorch
CMD ["jupyter", "notebook", "--allow-root", "--ip", "0.0.0.0", "--no-browser"]
```
And I use this docker image to run the following example script:
```bash
from pymatgen.core import Lattice, Structure
import matgl,os
os.environ["CUDA_VISIBLE_DEVICES"]=""
model = matgl.load_model("M3GNet-MP-2018.6.1-Eform")
# This is the structure obtained from the Materials Project.
struct = Structure.from_spacegroup("Pm-3m", Lattice.cubic(4.1437), ["Cs", "Cl"], [[0, 0, 0], [0.5, 0.5, 0.5]])
eform = model.predict_structure(struct)
print(f"The predicted formation energy for CsCl is {float(eform.numpy()):.3f} eV/atom.")
```
The log output is:
```bash
  File "/usr/local/lib/python3.9/site-packages/matgl/utils/io.py", line 210, in load_model
    mod = __import__(modname, globals(), locals(), [classname], 0)
  File "/usr/local/lib/python3.9/site-packages/matgl/models/__init__.py", line 5, in <module>
    from ._chgnet import CHGNet
  File "/usr/local/lib/python3.9/site-packages/matgl/models/_chgnet.py", line 19, in <module>
    from dgl import readout_edges, readout_nodes
  File "/usr/local/lib/python3.9/site-packages/dgl/__init__.py", line 16, in <module>
    from . import (
  File "/usr/local/lib/python3.9/site-packages/dgl/dataloading/__init__.py", line 13, in <module>
    from .dataloader import *
  File "/usr/local/lib/python3.9/site-packages/dgl/dataloading/dataloader.py", line 27, in <module>
    from ..distributed import DistGraph
  File "/usr/local/lib/python3.9/site-packages/dgl/distributed/__init__.py", line 5, in <module>
    from .dist_graph import DistGraph, DistGraphServer, edge_split, node_split
  File "/usr/local/lib/python3.9/site-packages/dgl/distributed/dist_graph.py", line 11, in <module>
    from .. import backend as F, graphbolt as gb, heterograph_index
  File "/usr/local/lib/python3.9/site-packages/dgl/graphbolt/__init__.py", line 55, in <module>
    load_graphbolt()
  File "/usr/local/lib/python3.9/site-packages/dgl/graphbolt/__init__.py", line 45, in load_graphbolt
    raise FileNotFoundError(
FileNotFoundError: Cannot find DGL C++ graphbolt library at /usr/local/lib/python3.9/site-packages/dgl/graphbolt/libgraphbolt_pytorch_2.4.0.so

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/crystal/examples/test_matgl.py", line 4, in <module>
    model = matgl.load_model("M3GNet-MP-2018.6.1-Eform")
  File "/usr/local/lib/python3.9/site-packages/matgl/utils/io.py", line 214, in load_model
    raise ValueError(
ValueError: Bad serialized model or bad model name. It is possible that you have an older model cached. Please clear your cache by running `python -c "import matgl; matgl.clear_cache()"`
```
It's perplexing that this error occurred despite using an environment created with the Dockerfile.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wangzyphysics** [comment]
Hi xiaohang007, I also encounter this error when using the latest version (matgl==1.1.3), How did you fix this error? 

(pip install matgl==1.1.3 -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple)

**Comment by xiaohang007** [comment]
> Hi xiaohang007, I also encounter this error when using the latest version (matgl==1.1.3), How did you fix this error?
> 
> (pip install matgl==1.1.3 -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple)

I forget about how to deal with it. So I output my env to package_conda.txt. And the setup.py used in installing my SLICES package is also provided (maybe helpful).
[setup.txt](https://github.com/user-attachments/files/17618685/setup.txt)
[package_conda.txt](https://github.com/user-attachments/files/17618682/package_conda.txt)
