### ISSUE TITLE
[Bug]: Training model from scratch

### ISSUE THREAD

**Issue by msehabibur** [materialsvirtuallab/matgl#444]
### Email (Optional)

rahma103@purdue.edu

### Version

v2023.1.1

### Which OS(es) are you using?

- [X] MacOS
- [ ] Windows
- [ ] Linux

### What happened?

I am using this code to train a model from scratch, but I always end up getting error messages being shown in the log output section:

### Code snippet

```python
I am using this code to train a model from scratch, but I always end up getting error messages being shown in the log output section:

from __future__ import annotations

import os
os.environ['LD_LIBRARY_PATH'] = '/apps/gilbreth/cuda-toolkit/cuda-11.2.0/lib64:' + os.environ.get('LD_LIBRARY_PATH', '')
import json
import dgl
import shutil
import warnings
import logging
import numpy as np
import pandas as pd
import ast
from pymatgen.core.structure import Structure
import torch
import pytorch_lightning as pl
from functools import partial
from pytorch_lightning.loggers import CSVLogger

# Import updated MGLDataset, MGLDataLoader, and collate_fn_pes
from mgl_data_utils import MGLDataset, MGLDataLoader, collate_fn_pes

import matgl
from matgl.ext.pymatgen import Structure2Graph
from matgl.models import M3GNet
from matgl.utils.training import PotentialLightningModule
from matgl.config import DEFAULT_ELEMENTS

print(dgl.__version__)
# Set up logging to file and console
log_file = "training.log"
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s', handlers=[
    logging.FileHandler(log_file),
    logging.StreamHandler()
])
logger = logging.getLogger(__name__)

logger.info("Script started...")

# To use GPU
torch.set_default_device("cuda")
logger.info(f"Is CUDA available: {torch.cuda.is_available()}")

# Set CUDA as the default tensor type
torch.set_default_dtype(torch.float32)
torch.set_float32_matmul_precision('medium')

# To suppress warnings for clearer output
warnings.simplefilter("ignore")

# Parse forces and stresses as arrays


# Load only the first 10 rows
df = pd.read_csv('/scratch/gilbreth/rahma103/Nov_5_2024/matgl/consolidated_data.csv')

# Parse the Forces and Stresses columns as arrays using json.loads
df['Forces_array'] = df['Forces'].apply(lambda x: np.array(json.loads(x)))
df['Stresses_array'] = df['Stress'].apply(lambda x: np.array(json.loads(x)).reshape(-1, 6) * -0.1)

# Parse the Structure column into pymatgen Structure objects
structures = [Structure.from_dict(json.loads(s)) for s in df['Structure']]

# Prepare energy, forces, and stress labels
energies = df['Energy'].tolist()
forces = [f.tolist() for f in df['Forces_array']]
stresses = [s.tolist() for s in df['Stresses_array']]

labels = {
    "energies": energies,
    "forces": forces,
    "stresses": stresses,
}



element_types = DEFAULT_ELEMENTS
converter = Structure2Graph(element_types=element_types, cutoff=5.0)

save_dir = './'
os.makedirs(save_dir, exist_ok=True)

dataset = MGLDataset(threebody_cutoff=4.0, structures=structures, converter=converter, labels=labels, include_line_graph=True, save_dir=save_dir)

train_data, val_data, test_data = dgl.data.utils.split_dataset(
    dataset,
    frac_list=[0.8, 0.1, 0.1],
    shuffle=True,
    random_state=42,
)

# if you are not intended to use stress for training, switch include_stress=False!
my_collate_fn = partial(collate_fn_pes, include_line_graph=True, include_stress=True)

# Create CUDA generator
generator = torch.Generator(device="cuda")
generator.manual_seed(42)
logger.info(f"Generator device: {generator.device}")

train_loader, val_loader, test_loader = MGLDataLoader(
    train_data=train_data,
    val_data=val_data,
    test_data=test_data,
    collate_fn=my_collate_fn,
    batch_size=16,
    num_workers=0,
    generator=generator,
)

# Check generator in DataLoader
logger.info(f"Train DataLoader generator device: {train_loader.generator.device}")
logger.info(f"Validation DataLoader generator device: {val_loader.generator.device}")

# download a pre-trained M3GNet
#m3gnet_nnp = matgl.load_model("M3GNet-MP-2021.2.8-PES")
#model_pretrained = m3gnet_nnp.model
#property_offset = m3gnet_nnp.element_refs.property_offset

# Define the M3GNet model
model = M3GNet(
    element_types=element_types,
    is_intensive=False,
)

lit_module_finetune = PotentialLightningModule(model=model, lr=5e-4, include_line_graph=True, stress_weight=0.01)

# If you wish to disable GPU or MPS (M1 mac) training, use the accelerator="cpu" kwarg.
logger.info("Setting up trainer...")
logger_csv = CSVLogger("logs", name="M3GNet_finetuning")
trainer = pl.Trainer(max_epochs=1, accelerator="gpu", devices=1, logger=logger_csv, inference_mode=False)
logger.info("Starting training...")
trainer.fit(model=lit_module_finetune, train_dataloaders=train_loader, val_dataloaders=val_loader)

# save trained model
model_save_path = "./"
lit_module_finetune.model.save(model_save_path)
logger.info(f"Model saved to {model_save_path}")
```

### Log output

```shell
INFO:    underlay of /etc/localtime required more than 50 (73) bind mounts
INFO:    underlay of /usr/bin/nvidia-cuda-mps-server required more than 50 (282) bind mounts
ldd (Ubuntu GLIBC 2.35-0ubuntu3.8) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
Mon Nov 25 02:33:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-16GB           On  | 00000000:3B:00.0 Off |                    0 |
| N/A   30C    P0              26W / 250W |      0MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
2024-11-25 02:34:23,071 - INFO - Script started...
2024-11-25 02:34:23,089 - INFO - Is CUDA available: True
2024-11-25 02:34:53,481 - INFO - Generator device: cuda
2024-11-25 02:34:53,482 - INFO - Train DataLoader generator device: cuda
2024-11-25 02:34:53,482 - INFO - Validation DataLoader generator device: cuda
2024-11-25 02:34:53,972 - INFO - Setting up trainer...
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2024-11-25 02:34:55,789 - INFO - Starting training...
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type              | Params
--------------------------------------------
0 | mae   | MeanAbsoluteError | 0     
1 | rmse  | MeanSquaredError  | 0     
2 | model | Potential         | 288 K 
--------------------------------------------
288 K     Trainable params
0         Non-trainable params
288 K     Total params
1.153     Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
2.1.0+cu118

Sanity Checking: |          | 0/? [00:00<?, ?it/s]
Sanity Checking:   0%|          | 0/2 [00:00<?, ?it/s]
Sanity Checking DataLoader 0:   0%|          | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/scratch/gilbreth/rahma103/Nov_5_2024/matgl/train.py", line 123, in <module>
    trainer.fit(model=lit_module_finetune, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1031, in _run_stage
    self._run_sanity_check()
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/trainer.py", line 1060, in _run_sanity_check
    val_loop.run()
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/loops/utilities.py", line 182, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 135, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx, dataloader_iter)
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 396, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/pytorch_lightning/strategies/strategy.py", line 412, in validation_step
    return self.lightning_module.validation_step(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/matgl/utils/training.py", line 59, in validation_step
    results, batch_size = self.step(batch)  # type: ignore
                          ^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/matgl/utils/training.py", line 415, in step
    results = self.loss_fn(
              ^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/matgl/utils/training.py", line 474, in loss_fn
    s_loss = loss(labels[2], preds[2], **self.loss_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/torch/nn/functional.py", line 3325, in mse_loss
    return handle_torch_function(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/torch/overrides.py", line 1604, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/torch/nn/functional.py", line 3338, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/depot/amannodi/apps/bigconda/envs/matgl/lib/python3.12/site-packages/torch/functional.py", line 76, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The size of tensor a (736) must match the size of tensor b (48) at non-singleton dimension 0
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kenko911** [comment]
@msehabibur, please go through the section on potential training in our repository. It clearly specifies the required format for stresses used in potential training
