### ISSUE TITLE
Running MD with the pre-trained model in GPU

### ISSUE THREAD

**Issue by HojeChun** [materialsvirtuallab/matgl#77]
Thanks for providing such an wonderful work.
I am trying to use pre-trained model "M3GNet-MP-2021.2.8-PES" to run MD simulation.
I wanted to run it on GPU. I placed the model to GPU but I got conflicting device issue.
Could you help me resolve it?

**Comment by shyuep** [comment]
Please post the short snippet of code you used to load the model to GPU.

**Comment by HojeChun** [comment]
Thanks for the quick reply!

- pytorch version: 2.0.1
- git commit hash: `c8d332e`

Ran the MD simulation with the python script as below
```python
import warnings

import ase.build
import matgl
from ase.md.velocitydistribution import MaxwellBoltzmannDistribution
from matgl.apps.pes import Potential
from matgl.ext.ase import M3GNetCalculator, MolecularDynamics, Relaxer
from matgl.models import M3GNet

# To suppress warnings for clearer output
warnings.simplefilter("ignore")


pot = matgl.load_model(
    "/home2/hojechun/github_repo/matgl/pretrained_models/M3GNet-MP-2021.2.8-PES"
)
pot.to("cuda")

## MD

calc = M3GNetCalculator(pot)
atoms = ase.build.bulk("Pt", cubic=True, a=3.92)
atoms.calc = calc

MaxwellBoltzmannDistribution(atoms, temperature_K=800)
driver = MolecularDynamics(
    atoms,
    potential=pot,
    temperature=800,
    trajectory="test_md.traj",
    logfile="test_md.log",
)
# Run
driver.run(250)
```

The error message was:
```
Traceback (most recent call last):
  File "/home2/hojechun/test/09-matgl/md_run_gpu_fail_reprod.py", line 34, in <module>
    driver.run(250)
  File "/home2/hojechun/github_repo/matgl/matgl/ext/ase.py", line 437, in run
    self.dyn.run(steps)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/md/md.py", line 137, in run
    return Dynamics.run(self)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/optimize/optimize.py", line 156, in run
    for converged in Dynamics.irun(self):
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/optimize/optimize.py", line 122, in irun
    self.atoms.get_forces()
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/atoms.py", line 788, in get_forces
    forces = self._calc.get_forces(self)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/calculators/abc.py", line 23, in get_forces
    return self.get_property('forces', atoms)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/ase/calculators/calculator.py", line 737, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home2/hojechun/github_repo/matgl/matgl/ext/ase.py", line 168, in calculate
    energies, forces, stresses, hessians = self.potential(graph, state_attr_default)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/hojechun/github_repo/matgl/matgl/apps/pes.py", line 73, in forward
    total_energies = self.data_std * self.model(g=g, state_attr=state_attr, l_g=l_g) + self.data_mean
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/hojechun/github_repo/matgl/matgl/models/_m3gnet.py", line 235, in forward
    num_node_feats, num_edge_feats, num_state_feats = self.embedding(node_types, g.edata["rbf"], state_attr)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/hojechun/github_repo/matgl/matgl/layers/_embedding.py", line 74, in forward
    node_feat = self.layer_node_embedding(node_attr)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/home2/hojechun/.conda/envs/matgl/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
```
